model:
  model_name: coop_multi_path
  prompt_template: ["a photo of x x", "a photo of x", "a photo of x"]
  ctx_init: ["a photo of ", "a photo of ", "a photo of "]
  clip_model: "ViT-L/14"
  # clip_arch: 
  # branch
  pair_loss_weight: 1.0
  pair_inference_weight: 1.0
  attr_loss_weight: 1.0
  attr_inference_weight: 1.0
  obj_loss_weight: 1.0
  obj_inference_weight: 1.0

train:
  dataset: ut-zappos
  # dataset_path: 
  optimizer: Adam
  scheduler: StepLR
  step_size: 3
  gamma: 0.5
  lr: 0.0003
  attr_dropout: 0.3
  weight_decay: 0.00002    # 0.00001
  context_length: 8
  train_batch_size: 128    # 64
  gradient_accumulation_steps: 2
  # seed:
  epochs: 20
  epoch_start: 0
  # save_path: 
  val_metric: AUC
  save_final_model: True
  # load_model: False     # False or model path

test:
  eval_batch_size: 64
  open_world: False
  # load_model: 
  topk: 1
  text_encoder_batch_size: 1024
  # threshold: 0.4
  threshold_trials: 50
  bias: 0.001
  text_first: True